from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "shared" / "agent-events.contract.ts"
TARGETS = (
    ROOT / "frontend" / "lib" / "agent-events.ts",
    ROOT / "gateway" / "src" / "types" / "agent-events.ts",
)
HEADER = "// Generated from shared/agent-events.contract.ts by scripts/sync_agent_event_types.py.\n// Do not edit this file directly.\n\n"


def main() -> int:
    content = SOURCE.read_text(encoding="utf-8").strip() + "\n"
    rendered = HEADER + content
    for target in TARGETS:
        target.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
